name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Check formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check src/

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger "console;verbosity=normal"

    - name: Check for build warnings
      run: |
        dotnet build --configuration Release --no-restore --warnaserror

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install FSharpLint
      run: dotnet tool install -g dotnet-fsharplint

    - name: Run FSharpLint
      run: dotnet fsharplint lint WhisperFS.sln

    - name: Check for TODOs
      run: |
        if grep -r "TODO\|FIXME\|HACK" --include="*.fs" --include="*.fsi" src/; then
          echo "::warning::Found TODO/FIXME/HACK comments in code"
        fi